version: 2
project_name: qbee-connect
builds:
  - builder: prebuilt
    targets:
      - "darwin_amd64"
      - "darwin_arm64"
      - "windows_amd64"
      - "linux_amd64"

    prebuilt:
      path: output/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ .ProjectName }}
    binary: "{{ .ProjectName }}"

gomod:
  proxy: true

changelog:
  use: github-native

sboms:
  - artifacts: source

checksum:
  name_template: checksums.txt

source:
  enabled: true

archives:
   - formats: [ 'tar.gz' ]

nfpms:
    - vendor: qbee AS
      homepage: https://qbee.io/
      maintainer: The Qbee Team <support@qbee.io>
      license: Apache-2.0

      description: Qbee Connect Desktop Utility

      file_name_template: "{{- .ConventionalFileName -}}"

      priority: extra
      section: default

      formats:
        - deb
        - rpm

      dependencies:
        - libgl1
        - libxcursor1
        - libxi6
        - libxinerama1
        - libxrandr2
        - libxxf86vm1

      overrides:
        rpm:
          dependencies:
            - mesa-libGL
            - libXcursor
            - libXi
            - libXinerama
            - libXrandr
            - libXxf86vm

      contents:
        - src: linux/qbee-connect.desktop
          dst: /usr/share/applications/qbee-connect.desktop
          file_info:
            mode: 644
            owner: root
            group: root

        - src: internal/ui/qbee-connect.png
          dst: /usr/share/pixmaps/qbee-connect.png
          file_info:
            mode: 644
            owner: root
            group: root

msi:
  - name: "{{ .ProjectName }}_{{ .Version }}_{{ .MsiArch }}"
    wxs: ./windows/qbee-connect.wks
    extra_files:
      - windows/qbee.ico
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    version: v3

app_bundles:
  - icon: darwin/qbee.icns
    bundle: io.qbee.qbee-connect
    name: "{{ .ProjectName }}"
    id: "{{ .ProjectName }}_{{ .Arch }}"

dmg:
  - name: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    use: appbundle
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    ids:
      - "{{ .ProjectName }}_{{ .Arch }}"

notarize:
  macos_native:
    - enabled: "true"
      sign:
        keychain: "{{ .Env.KEYCHAIN_PATH }}"
        identity: "{{ .Env.MACOS_SIGN_IDENTITY }}"
        options: [runtime]

      notarize:
        profile_name: "{{ .Env.MACOS_NOTARY_PROFILE_NAME }}"
        wait: true

