version: 2
project_name: qbee-connect
builds:
  - builder: prebuilt
    targets:
      - "darwin_amd64"
      - "darwin_arm64"
      - "windows_amd64"
      - "linux_amd64"

    prebuilt:
      path: output/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ .ProjectName }}
    binary: bin/{{ .ProjectName }}

gomod:
  proxy: true

changelog:
  use: github-native

sboms:
  - artifacts: source

checksum:
  name_template: checksums.txt

source:
  enabled: true

archives:
   - formats: [ 'tar.gz' ]

msi:
  - name: "{{ .ProjectName }}_{{ .Version }}_{{ .MsiArch }}"
    wxs: ./windows/qbee-connect.wks
    extra_files:
      - windows/qbee.ico
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    version: v3

app_bundles:
  - icon: darwin/qbee.icns
    bundle: io.qbee.qbee-connect
    name: "{{ .ProjectName }}_{{ .Arch }}"

dmg:
  - name: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    use: appbundle
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"

notarize:
  macos_native:
    - enabled: "true"
      sign:
        keychain: "{{ .Env.KEYCHAIN_PATH }}"
        identity: "{{ .Env.MACOS_SIGN_IDENTITY }}"
        options: [runtime]

      notarize:
        profile_name: "{{ .Env.MACOS_NOTARY_PROFILE_NAME }}"
        wait: true

