name: build and upload artifacts

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  attestations: write # needed for provenance

on:
  release:
    types: [created]


env:
  # VERSION is set to the release tag name, e.g., "1.0.0".
  VERSION: 26.8.1

  # BUILD_NUMBER is set to the run number of the workflow.
  BUILD_NUMBER: 1

jobs:
  linux-pkgs:
    name: Linux Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install stable Go version
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install Fyne tool
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Installing OS dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

      - name: Build binary
        run: fyne package --release --app-version ${{ env.VERSION }} --app-build ${{ env.BUILD_NUMBER }}

      - name: Upload package to the release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ env.VERSION }} qbee-connect_${{ env.VERSION }}_amd64${{ matrix.ext }} --clobber

  release:
    name: Create Release
    if: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download installers non-MacOS
        uses: actions/download-artifact@v6
        with:
          pattern: artifacts-*
          path: dist
          merge-multiple: true

      - name: Install Cosign for attestation and signing
        uses: sigstore/cosign-installer@v3.10.1

      - name: Install Syft for SBOM generation
        uses: anchore/sbom-action/download-syft@v0.20.10

      - name: Run goreleaser-pro
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          install-only: true

      - name: Create Release
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser continue --merge
