name: build and upload artifacts

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  attestations: write # needed for provenance

on:
  release:
    types: [created]

jobs:
  build:
    name: build and upload artifacts
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            target: windows
            cc: x86_64-w64-mingw32-gcc
            ext: .exe
          - os: ubuntu-24.04
            arch: amd64
            target: linux

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all git tags
        run: git fetch --prune --unshallow --tags

      - name: installing Linux dependencies
        if: matrix.target == 'linux'
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

      - name: installing Windows dependencies
        if: matrix.target == 'windows'
        shell: bash
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          curl https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
          sudo dpkg -i --force-confnew packages-microsoft-prod.deb

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false # We are using custom caching below because cache key depends on target and arch, not go.sum, go.mod, go version and OS.

      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ matrix.target }}-${{ matrix.arch }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.target }}-${{ matrix.arch }}-golang-

      - name: install go dependencies
        shell: bash
        run: |
          go install fyne.io/tools/cmd/fyne@latest

      - name: Set environment variables
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV

      - name: Extract version
        id: extract_version
        run: |
          REF_NAME=${GITHUB_REF_NAME}
          SHA_SHORT="${GITHUB_SHA:0:7}"
          
          QBEE_CONNECT_VERSION="0.0.0~${SHA_SHORT}"
          if [[ "${GITHUB_REF}" == "refs/tags/"* ]]; then
            QBEE_CONNECT_VERSION=$REF_NAME
          fi
          echo "Version = \"${QBEE_CONNECT_VERSION}\"" >> FyneApp.toml
          echo "Build = ${{ github.run_number }}" >> FyneApp.toml
          
      - name: Build binary for ${{ matrix.target }} on ${{ matrix.arch }}
        shell: bash
        run: |
          GOARCH=${{ matrix.arch }} fyne build \
            --release \
            --target ${{ matrix.target }} \
            --output $GITHUB_WORKSPACE/build/qbee-connect
     
      - name: Upload qbee-connect binary
        uses: actions/upload-artifact@v4
        with:
          name: qbee-connect_${{ matrix.target }}_${{ matrix.arch }}
          path: |
            build/qbee-connect*
          if-no-files-found: error
          retention-days: 7

  build-artifacts-linux-windows:
    name: Build installers non-MacOS
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download qbee-connect binaries
        uses: actions/download-artifact@v6
        with:
          path: output

      - name: Run goreleaser-pro
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          install-only: true
      
      - name: Install packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wixl

      - name: Build installers
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
        run: |
          goreleaser release --split
          GOOS=windows goreleaser release --split

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux-windows
          path: dist/
          if-no-files-found: error
          retention-days: 7

      - name: Run goreleaser-pro
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          install-only: true

      - name: Build installers
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          MACOS_SIGN_IDENTITY: ${{ secrets.MACOS_SIGN_IDENTITY }}
          MACOS_NOTARY_PROFILE_NAME: ${{ secrets.MACOS_NOTARY_PROFILE_NAME }}
        run: |
          goreleaser release --split

          # remove symlinks from dist directory to avoid upload issues
          # in Github Actions with circular references
          find dist/darwin -type l -exec rm {} +

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-macos
          path: dist/
          if-no-files-found: error
          retention-days: 7

  release:
    name: Create Release
    needs:
      - build-artifacts-linux-windows
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download installers non-MacOS
        uses: actions/download-artifact@v6
        with:
          pattern: artifacts-*
          path: dist
          merge-multiple: true

      - name: Install Cosign for attestation and signing
        uses: sigstore/cosign-installer@v3.10.1

      - name: Install Syft for SBOM generation
        uses: anchore/sbom-action/download-syft@v0.20.10

      - name: Run goreleaser-pro
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          install-only: true

      - name: Create Release
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser continue --merge
